import { DeliveryOrder, CustomerProfile, DriverInfo, ChatMessage } from '@/types/delivery';

export const initialCustomerProfile: CustomerProfile = {
  firstName: 'Chidinma',
  lastName: 'Adeleke',
  phone: '0803 456 7890',
  email: 'chidinma.adeleke@example.com',
};

export const sampleDriver: DriverInfo = {
  name: 'Babajide Sanusi',
  phone: '0812 345 6789',
  rating: 4.9,
  totalDeliveries: 1240,
  vehicleModel: 'Toyota Corolla • Silver',
  vehiclePlate: 'LAG-492-APP',
  currentLocationName: 'Ozumba Mbadiwe Ave, Victoria Island (1.5 km away)',
};

export const sampleOrders: DeliveryOrder[] = [
  {
    id: 'ord-101',
    trackingNumber: 'TRK-984210',
    status: 'in_transit',
    createdAt: 'Today, 09:15 AM',
    estimatedDelivery: 'Today, 02:30 PM',
    sender: {
      fullName: 'Chidinma Adeleke',
      phone: '0803 456 7890',
      address: '14 Admiralty Way, Lekki Phase 1',
      apartment: 'Block B, Flat 4',
      city: 'Lagos',
      postalCode: '105102',
      pickupTimeWindow: 'Morning (09:00 - 11:00 AM)',
      pickupNotes: 'Call security gate on arrival, flat is on 2nd floor',
    },
    receiver: {
      fullName: 'Tunde Balogun',
      phone: '0814 555 1234',
      address: '28 Isaac John Street, GRA',
      apartment: 'Suite 2A',
      city: 'Ikeja, Lagos',
      postalCode: '100271',
      deliveryInstructions: 'Call upon arrival, do not leave at reception unattended',
    },
    packageInfo: {
      category: 'medium_box',
      weight: 3.4,
      description: 'Solar Inverter Accessories & Hardware',
      isFragile: true,
      requiresSignature: true,
    },
    payment: {
      method: 'card',
      baseFare: 2500,
      distanceFare: 3500,
      weightFare: 1200,
      insurance: 800,
      discount: 1000,
      total: 7000,
      promoCode: 'EXPRESS5',
      cardNumberMasked: '•••• 4242',
    },
    driver: sampleDriver,
    timeline: [
      {
        status: 'confirmed',
        title: 'Order Confirmed',
        description: 'Payment authorized and dispatch courier assigned.',
        timestamp: '09:15 AM',
        completed: true,
        current: false,
      },
      {
        status: 'in_transit',
        title: 'In Transit',
        description: 'Package picked up from Lekki Hub, moving across Lekki-Ikoyi Link Bridge.',
        timestamp: '10:45 AM',
        completed: true,
        current: true,
      },
      {
        status: 'out_for_delivery',
        title: 'Out for Delivery',
        description: 'Assigned to dispatch driver Babajide Sanusi for Ikeja delivery.',
        timestamp: 'Est. 01:45 PM',
        completed: false,
        current: false,
      },
      {
        status: 'delivered',
        title: 'Delivered',
        description: 'Package handed over with digital signature verification.',
        timestamp: 'Est. 02:30 PM',
        completed: false,
        current: false,
      },
    ],
  },
  {
    id: 'ord-102',
    trackingNumber: 'TRK-881903',
    status: 'out_for_delivery',
    createdAt: 'Today, 07:30 AM',
    estimatedDelivery: 'Today, 11:45 AM (Arriving soon)',
    sender: {
      fullName: 'Amina Bello',
      phone: '0802 334 5566',
      address: '12 Gana Street, Maitama',
      city: 'Abuja',
      postalCode: '900271',
      pickupTimeWindow: 'Early Morning (07:30 - 09:00 AM)',
    },
    receiver: {
      fullName: 'Chidinma Adeleke',
      phone: '0803 456 7890',
      address: '14 Admiralty Way, Lekki Phase 1',
      apartment: 'Block B, Flat 4',
      city: 'Lagos',
      postalCode: '105102',
      deliveryInstructions: 'Hand over to security if unavailable',
    },
    packageInfo: {
      category: 'small_box',
      weight: 1.2,
      description: 'CAC Corporate Documents & Legal Seals',
      isFragile: false,
      requiresSignature: true,
    },
    payment: {
      method: 'bank_transfer',
      baseFare: 4500,
      distanceFare: 7500,
      weightFare: 1500,
      insurance: 1500,
      discount: 0,
      total: 15000,
    },
    driver: {
      name: 'Emeka Okafor',
      phone: '0805 123 9876',
      rating: 4.95,
      totalDeliveries: 2890,
      vehicleModel: 'Bajaj Boxer Motorcycle • Red',
      vehiclePlate: 'ABJ-814-KJA',
      currentLocationName: 'Ahmadu Bello Way (1.2 km away)',
    },
    timeline: [
      {
        status: 'confirmed',
        title: 'Order Confirmed',
        description: 'Courier request booked and scheduled.',
        timestamp: '07:30 AM',
        completed: true,
        current: false,
      },
      {
        status: 'in_transit',
        title: 'In Transit',
        description: 'Sorted at Central Hub and dispatched.',
        timestamp: '08:45 AM',
        completed: true,
        current: false,
      },
      {
        status: 'out_for_delivery',
        title: 'Out for Delivery',
        description: 'Emeka is 2 streets away from your delivery destination.',
        timestamp: '11:15 AM',
        completed: true,
        current: true,
      },
      {
        status: 'delivered',
        title: 'Delivered',
        description: 'Recipient handoff with proof of delivery.',
        timestamp: 'Est. 11:45 AM',
        completed: false,
        current: false,
      },
    ],
  },
  {
    id: 'ord-103',
    trackingNumber: 'TRK-741295',
    status: 'delivered',
    createdAt: 'Yesterday, 02:00 PM',
    estimatedDelivery: 'Yesterday, 05:14 PM',
    sender: {
      fullName: 'Chidinma Adeleke',
      phone: '0803 456 7890',
      address: '14 Admiralty Way, Lekki Phase 1',
      city: 'Lagos',
      postalCode: '105102',
      pickupTimeWindow: 'Afternoon',
    },
    receiver: {
      fullName: 'Ngozi Okonjo',
      phone: '0818 776 2211',
      address: '5 Aba Road, Old GRA',
      city: 'Port Harcourt',
      postalCode: '500101',
      deliveryInstructions: 'Leave with front desk executive',
    },
    packageInfo: {
      category: 'documents',
      weight: 0.8,
      description: 'Original Land Titles & Deeds',
      isFragile: false,
      requiresSignature: true,
    },
    payment: {
      method: 'card',
      baseFare: 3000,
      distanceFare: 6500,
      weightFare: 1000,
      insurance: 1500,
      discount: 1000,
      total: 11000,
      cardNumberMasked: '•••• 4242',
    },
    driver: {
      name: 'Kayode Alabi',
      phone: '0903 445 1199',
      rating: 4.88,
      totalDeliveries: 940,
      vehicleModel: 'Suzuki Every Cargo Van',
      vehiclePlate: 'RIV-302-PHC',
      currentLocationName: 'Delivered',
    },
    timeline: [
      {
        status: 'confirmed',
        title: 'Order Confirmed',
        description: 'Order confirmed and paid.',
        timestamp: '02:00 PM',
        completed: true,
        current: false,
      },
      {
        status: 'in_transit',
        title: 'In Transit',
        description: 'Courier picked up package.',
        timestamp: '03:10 PM',
        completed: true,
        current: false,
      },
      {
        status: 'out_for_delivery',
        title: 'Out for Delivery',
        description: 'Driver approached destination.',
        timestamp: '04:45 PM',
        completed: true,
        current: false,
      },
      {
        status: 'delivered',
        title: 'Delivered',
        description: 'Signed for by Recipient: Ngozi O.',
        timestamp: '05:14 PM',
        completed: true,
        current: true,
      },
    ],
  },
  {
    id: 'ord-104',
    trackingNumber: 'TRK-619024',
    status: 'confirmed',
    createdAt: 'Today, 10:45 AM',
    estimatedDelivery: 'Tomorrow, 10:00 AM',
    sender: {
      fullName: 'Chidinma Adeleke',
      phone: '0803 456 7890',
      address: '14 Admiralty Way, Lekki Phase 1',
      city: 'Lagos',
      postalCode: '105102',
      pickupTimeWindow: 'Tomorrow Morning',
    },
    receiver: {
      fullName: 'Alhaji Usman Danjuma',
      phone: '0809 667 8899',
      address: '44 Bompai Road, Nassarawa',
      city: 'Kano',
      postalCode: '700213',
    },
    packageInfo: {
      category: 'cargo',
      weight: 14.5,
      description: 'Aso Oke Textiles & Fashion Accessories',
      isFragile: true,
      requiresSignature: true,
    },
    payment: {
      method: 'bank_transfer',
      baseFare: 6000,
      distanceFare: 14000,
      weightFare: 6000,
      insurance: 2000,
      discount: 2000,
      total: 26000,
    },
    timeline: [
      {
        status: 'confirmed',
        title: 'Order Confirmed',
        description: 'Order created, awaiting scheduled pickup window tomorrow.',
        timestamp: '10:45 AM',
        completed: true,
        current: true,
      },
      {
        status: 'in_transit',
        title: 'In Transit',
        description: 'Package will be collected and loaded into regional transit.',
        timestamp: 'Scheduled',
        completed: false,
        current: false,
      },
      {
        status: 'out_for_delivery',
        title: 'Out for Delivery',
        description: 'Final courier assignment for local delivery.',
        timestamp: 'Pending',
        completed: false,
        current: false,
      },
      {
        status: 'delivered',
        title: 'Delivered',
        description: 'Package handover and signature receipt.',
        timestamp: 'Pending',
        completed: false,
        current: false,
      },
    ],
  },
];

export const initialChatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    sender: 'agent',
    text: 'Hello! Welcome to SwiftDrop Courier Support. How can we help you with your deliveries today?',
    timestamp: 'Just now',
  },
];

export const cannedFaqs = [
  'Where is my current delivery?',
  'Can I change my delivery address?',
  'Call or message my driver',
  'What happens if I miss a delivery?',
];
